---
title: "Lab 12 - Smoking during pregnancy"
author: "Yiwei Tang"
date: "2/19/2026"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(tidymodels)
library(openintro)
data(ncbirths)
```

### Exercise 1

fage, mage, weeks, visits, gained, and weight are numerical variables. fage, mage, visits, and gained are skewed to the right with some outliers. weeks and weight are skewed to the left with outliers.

```{r summary}
summary(ncbirths)
```

```{r fage}
ncbirths %>% 
  ggplot(
    aes(
      x = fage,
    )
  ) +
  geom_boxplot() +
  theme_minimal()
```

```{r mage}
ncbirths %>% 
  ggplot(
    aes(
      x = mage,
    )
  ) +
  geom_boxplot() +
  theme_minimal()
```

```{r weeks}
ncbirths %>% 
  ggplot(
    aes(
      x = weeks,
    )
  ) +
  geom_boxplot() +
  theme_minimal()
```


```{r visits}
ncbirths %>% 
  ggplot(
    aes(
      x = visits,
    )
  ) +
  geom_boxplot() +
  theme_minimal()
```

```{r gained}
ncbirths %>% 
  ggplot(
    aes(
      x = gained,
    )
  ) +
  geom_boxplot() +
  theme_minimal()
```

```{r weight}
ncbirths %>% 
  ggplot(
    aes(
      x = weight,
    )
  ) +
  geom_boxplot() +
  theme_minimal()
```

### Exercise 2

...

Add exercise headings as needed.
